################################################################################
#
# libindi_3rdparty
#
################################################################################

LIBINDI_3RDPARTY_VERSION = v1.6.2
LIBINDI_3RDPARTY_SITE = https://github.com/indilib/indi/releases/download/$(LIBINDI_VERSION)
LIBINDI_3RDPARTY_SOURCE = libindi_3rdparty_$(subst v,,$(LIBINDI_VERSION)).tar.gz
LIBINDI_3RDPARTY_INSTALL_STAGING = NO
LIBINDI_3RDPARTY_INSTALL_TARGET = YES
LIBINDI_3RDPARTY_DEPENDENCIES = libindi

ifeq ($(BR2_PACKAGE_LIBINDI_INDI_EQMOD),y)
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_EQMOD=ON
LIBINDI_3RDPARTY_DEPENDENCIES += libnova zlib gsl
else
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_EQMOD=OFF
endif

LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_SX=OFF
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_MAXDOME=OFF
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_NEXDOME=OFF
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_SPECTRACYBER=OFF
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_CLOUDWATCHER=OFF
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_NSE=OFF
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_GPHOTO=OFF
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_QSI=OFF #Library libqsi
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_SBIG=OFF #Library libsbig
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_INOVAPLX=OFF #Library libinovasdk
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_FLI=OFF #Library libfli
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_APOGEE=OFF #Library libapogee
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_MI=OFF
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_DUINO=OFF
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_FISHCAMP=OFF #Library libfishcamp

ifeq ($(BR2_PACKAGE_LIBINDI_INDI_ASI),y)
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_ASICAM=ON
LIBINDI_3RDPARTY_DEPENDENCIES += cfitsio zlib libusb
else
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_ASICAM=OFF
endif

LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_DSI=OFF
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_QHY=OFF #Library libqhy
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_GPSD=OFF
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_GPSNMEA=OFF
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_GIGE=OFF
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_MGEN=OFF
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_RTLSDR=OFF #Library libdspau
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_RADIOSIM=OFF

ifeq ($(BR2_PACKAGE_LIBINDI_INDI_SSAG),y)
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_SSAG=ON
LIBINDI_3RDPARTY_DEPENDENCIES += libusb
else
LIBINDI_3RDPARTY_CONF_OPTS += -DWITH_SSAG=OFF
endif

$(eval $(cmake-package))

